FROM node:20-alpine

WORKDIR /server

ENV NODE_ENV=production

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn/releases .yarn/releases

RUN yarn install

COPY . .

RUN sed -i 's/\r$//' ./start.prod.sh && chmod +x ./start.prod.sh
RUN yarn build

EXPOSE 9000

CMD ["sh", "-c", "sed -i 's/\\r$//' /server/start.prod.sh; sh /server/start.prod.sh"]